### ISSUE TITLE
OAuth login returns "invalid password" message

### ISSUE THREAD

**Issue by svenseeberg** [waldhacker/ext-oauth2-client#17]
I have an OAuth2 provider configured. After the OAuth provider redirects back to the TYPO3 back end, the following message is being logged:
```
Tue, 11 Apr 2023 12:08:08 +0000 [WARNING] request="5aaf2e1d4c04a" component="TYPO3.CMS.Core.Authentication.AuthenticationService": Login-attempt from MY_IP, for username "" with an empty password! - {"ip":"MY_IP","username":""}
```
The browser ends up at the following path: `/typo3/login?loginProvider=1616569531&oauth2-provider=MY_PROVIDER&login_status=login&commandLI=attempt&state=MY_STATE&session_state=MY_SESSION_STATE&code=MY_CODE`

As far as I can tell this is how it should be according to https://docs.typo3.org/p/waldhacker/typo3-oauth2-client/2.0/en-us/Configuration/Index.html#backend. I'm using TYPO3 v11. The IdP is Keycloak. I expect that there is something missing in the configuration. However, the log message does not provide any insight into what is wrong. An empty password should not be a thing for OAuth.

In my case the problem is that `buildGetResourceOwnerProvider` returns null (https://github.com/waldhacker/ext-oauth2-client/blob/develop/Classes/Service/Oauth2Service.php#L66) because `$oauth2StateFromSession` is null.

**Comment by maikschneider** [comment]
Hey @svenseeberg,

I had exactly the same issue. My problem was the default cookie setting `strict`, setting it to `lax` resolved my issue:

```php
$GLOBALS['TYPO3_CONF_VARS']['BE']['cookieSameSite'] = 'lax';
```

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/17).
