### ISSUE TITLE
Registered class League\OAuth2\Client\Provider\Google does not exist

### ISSUE THREAD

**Issue by HorstBaumann** [waldhacker/ext-oauth2-client#18]
... or is not an implementation of League\OAuth2\Client\Provider\AbstractProvider

After setting up everything by the tutorial (for google oauth https://docs.typo3.org/p/waldhacker/typo3-oauth2-client/2.0/en-us/Configuration/Google.html),
I get this message, when I switch to the backend user settings or try to call the callback URL

TYPO3: 10.4.34
oauth2_client: 2.0.1
Installation: classic/extensionmanager (no composer)

Does oauth2_client has an onboard GenericProvider?
Or is it necessary to install "league/oauth2-google:^4.0" ? - if so: How do I install "league/oauth2-google:^4.0" without composer ?

**Comment by waldhacker1** [comment]
Duplicate of #6  and #14 .
I will try to deploy to TER by hand this week.
The problem should then be solved.

**Comment by HorstBaumann** [comment]
oh, I did not see these entries - sorry.
and thanks a lot !
