### ISSUE TITLE
No provider is shown on new FE user or editing an FE user

### ISSUE THREAD

**Issue by jori-cicklum** [waldhacker/ext-oauth2-client#20]
- Currently on typo3 11.5
- the package was installed via composer
- there was not version 1 installed before
- the backend login works well
- the root site is not the main root site, is one level down
- I have iterated the docs more a million times
- Debugging the code, the problem seems to be that do not recognizes any of the **configured providers** as **active providers db**, even do is configured as in the documentation
- Waldhacker\Oauth2Client\Backend\Form\RenderType\Oauth2ProvidersElement::render() line 67, $this->data['parameterArray']['fieldConf']['children'] is empty

**Comment by miriamsass** [comment]
I had the same issue and it took me a while to figure it out. You can't add providers for frontend users via backend. They have to do it themselves in the frontend with the provided "Manage OAuth2 providers" plugin. The info in the backend just shows if they did enable it or not. 
The user guide is a bit misleading when it says "Go into your user settings". Maybe you could add a hint or something that those settings are found in the "Manage OAuth2 providers" plugin?

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/20).
