### ISSUE TITLE
Redirect after login with language 

### ISSUE THREAD

**Issue by CrosClemence** [waldhacker/ext-oauth2-client#21]
Hello @waldhacker1 , 
I'm using TYPO3 11.5.28 and login with Keycloak.

I'm using the feature "oauth2.frontend.login.afterOauth2RedirectUriFromQuery" since I want to redirect my user after login to a specific page into my website.

My problem is the following : 
- My user authenticate himself : working fine
- TYPO3 authenticate the user : working fine
- The extension is doing a matching of url to redirect to a specific url : KO

My host url is https://url_website/en
But Uri from TYPO3 returns https://url_website/ 

Is it a problem from my configuration ?
My root level is https://url_website/
Language levels are :
- https://url_website/en 
- https://url_website/fr
- https://url_website/es

I changed into the Class "RedirectRequestService" the function "isSameSite" to remove the language check this way it's working temporary on my website.

kind regards

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/21).
