### ISSUE TITLE
Wrong ext_emconf.php loaded in non-composer mode

### ISSUE THREAD

**Issue by ghost** [waldhacker/ext-oauth2-client#22]
I installed this extension from the TER and encountered the same error as in #14 

After some digging I found, that in one of the last commits, this should have been fixed by providing an alternative ext_emconf for the TER build process. However the "new" emconf is not shipped with the version from the TER.

I deleted the original ext_emconf on my system and replaced it with the version from `build/release/ext_emconf.php` now everything is working as expected.

[Typo3 11.5.23] non-composer

**Comment by AqujZ1K9** [comment]
same here +1

**Comment by agendartobias** [comment]
same here +1

**Comment by ghost** [comment]
It appears, that if you download the extension directly from TER, the correct ext_emconf is present. But if you use the extension manager backend module, the wrong emconf is shipped.

<details>

<summary>The falsy, shipped ext_emconf</summary>

```
<?php

/***************************************************************
 * Extension Manager/Repository config file for ext "oauth2_client".
 *
 * Auto generated 14-09-2023 10:14
 *
 * Manual updates:
 * Only the data in the array - everything else is removed by next
 * writing. "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'OAuth2 Client',
  'description' => 'TYPO3 OAuth2 Login Client (backend and frontend)',
  'category' => 'auth',
  'version' => '2.1.1',
  'state' => 'stable',
  'uploadfolder' => false,
  'clearcacheonload' => false,
  'author' => 'waldhacker',
  'author_email' => 'hello@waldhacker.dev',
  'author_company' => 'waldhacker UG (haftungsbeschränkt)',
  'constraints' =>
  array (
    'depends' =>
    array (
      'backend' => '10.4.0-11.5.99',
      'fluid' => '10.4.0-11.5.99',
      'setup' => '10.4.0-11.5.99',
      'typo3' => '10.4.0-11.5.99',
      'php' => '7.4.0-8.1.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);

```

</details>

Notice the "autogenerated" header.

My guess would be that Typo3s validation of the ext_emconf, that should be shipped, fails somehow and therefore Typo3 replaces the ext_emconf with an autogenerated version.

I took a look into the ext_emconf documentation and the only thing I noticed is that the `category` is set to `auth` which appears not be a valid option. I suggest to change that to `misc`.

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/22).
