### ISSUE TITLE
Different credentials/options (clientid, clientsecret etc.) for BE and FE Login.

### ISSUE THREAD

**Issue by smtxdev** [waldhacker/ext-oauth2-client#24]
Hello,

is there currently a way to have different credentials/options for BE and FE?

**Comment by maikschneider** [comment]
OAuth provider are added to existing BE or FE user accounts. Of cause these accounts can have different credentials.
If you want to create users via OAuth, you could check out [this extensions](https://github.com/xima-media/xima-oauth2-extended). There you can set default backend and frontend usergroups.

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/24).

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/24).
