### ISSUE TITLE
Waldhacker.Oauth2Client.Service.Oauth2Service Failed to parse JSON response - with Keycloak 21.1.1 and 23.0.1

### ISSUE THREAD

**Issue by thorsten-l** [waldhacker/ext-oauth2-client#25]
I've installed Typo3 11.5.33 + oauth 2_client via composer and followed the documentation for Keycloak.

The following error is showing in the log:
```
Fri, 08 Dec 2023 10:16:06 +0000 [WARNING] request="f9ba586f6c809" component="Waldhacker.Oauth2Client.Service.Oauth2Service": Failed to parse JSON response: Syntax error
Fri, 08 Dec 2023 10:16:06 +0000 [WARNING] request="f9ba586f6c809" component="TYPO3.CMS.Core.Authentication.AuthenticationService": Login-attempt from 192.168.65.1, for username "" with an empty password! - {"ip":"192.168.65.1","username":""}
```

If i check the login to Keycloak using an OIDC dummy program dealing with the exactly the same configuration everything works fine.

**Comment by Loeffeldude** [comment]
So first the documentation is pretty outdated. The urls have changed from /auth/realms to just /realms. Additionally this extension gets the user info from `/realms/<realm>/protocol/openid-connect/userinfo` which requires the openid scope. A configuration that worked for me is this:

```php
'providers' => [
      'keycloak' => [
        'label' => 'Keycloak',
        'description' => 'Login with Keycloak',
        'scopes' => [
          \Waldhacker\Oauth2Client\Service\Oauth2ProviderManager::SCOPE_BACKEND,
          \Waldhacker\Oauth2Client\Service\Oauth2ProviderManager::SCOPE_FRONTEND,
        ],
        'options' => [
          'clientId' => <client_id>,
          'clientSecret' => <client_secret>,
          'urlAuthorize' => 'https://<keycloak-host>/realms/<realm>/protocol/openid-connect/auth',
          'urlAccessToken' => 'https://<keycloak-host>/realms/<realm>/protocol/openid-connect/token',
          'urlResourceOwnerDetails' => 'https://<keycloak-host>/realms/<realm>/protocol/openid-connect/userinfo',
          'responseResourceOwnerId' => 'sub',
          'scopes' => ['openid', 'profile', 'email'],
          'scopeSeparator' => ' ',
        ],
      ],
    ],
``` 

I also created the openid scope globally because it only needs to passed in the login or something but it was easy just to create a new scope. Don't know if this last step is necessary.

**Comment by waldhacker1** [comment]
The Issue has been moved to [GitLab](https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/issues/25).
