### ISSUE TITLE
Copying content element doesn't work in page module

### ISSUE THREAD

**Issue by hulgor** [waldhacker/ext-oauth2-client#3]
After setting up our project (TYPO3 11.5) with ext-oauth-client it turned out that copied content elements (in page module) can't be inserted any more. Copy & paste in the list module works fine. After removing the extension from the oroject copy & paste works too.
Due to to the logging file, a type error causes the exception:

`Exception handler (WEB: BE): TypeError, code #0, file /var/www/html/public/typo3conf/ext/oauth2_client/Classes/DataHandling/DataHandlerHook.php, line 75: Argument 7 passed to Waldhacker\Oauth2Client\DataHandling\DataHandlerHook::processCmdmap() must be of the type bool, array given, called in /var/www/html/public/typo3/sysext/core/Classes/DataHandling/DataHandler.php on line 3132- TypeError: Argument 7 passed to Waldhacker\Oauth2Client\DataHandling\DataHandlerHook::processCmdmap() must be of the type bool, array given, called in /var/www/html/public/typo3/sysext/core/Classes/DataHandling/DataHandler.php on line 3132, in file /var/www/html/public/typo3conf/ext/oauth2_client/Classes/DataHandling/DataHandlerHook.php:75`

After debugging and removing line 3116 `$pasteUpdate = $value['update'];` in typo3/sysext/core/Classes/DataHandling/DataHandler.php all copy & paste and move functions are working again.

Where's the difference between the page and the list module considering the way of copying content elements (while using th ext-oauth-client) ?

**Comment by felixranesberger** [comment]
We are having similar issues right now, is there an update on the problem?

**Comment by waldhacker1** [comment]
Should be resolved with version 1.0.1
Please re-open the ticket if the problem still exists.
