### ISSUE TITLE
extension class loading not working with typo3 11.5.10

### ISSUE THREAD

**Issue by playernine** [waldhacker/ext-oauth2-client#6]
Hi.

Maybe I found a problem or I do something wrong.

I installed the oauth-client Plugin directly the typo3 extension repo.

Environment:

Ubuntu 20.04 
PHP 7.4.3-4ubuntu2.10
Typo3 11.5.10
pizpalue_distribution 3.3.1

Message from Typo3 log:

Core:  Exception handler (WEB): Uncaught TYPO3 Exception: #1642867945:  Registered class League\OAuth2\Client\Provider\GenericProvider does not  exist or is not an implementation of  League\OAuth2\Client\Provider\AbstractProvider \|  InvalidArgumentException thrown in file  /var/www/html/typo3/typo3conf/ext/oauth2_client/Classes/Domain/Model/ProviderConfiguration.php  in line 49. Requested URL: https://www-t3.ostfalia.de/favicon.ico |  

I think the autoload stuff is not working with this plugin.

I use the GenericProvider and added the the config at /var/www/html/typo3/typo3conf/AdditionalConfiguration.php

If I add the missing classes from 

/var/www/html/typo3/typo3conf/ext/oauth2_client/Resources/Private/PHP/composer/autoload_classmap.php

into to the central autoload_classmap.php 

/var/www/html/typo3/typo3conf/autoload/autoload_classmap.php

it seems to work better, but not complete. I get no Exceptions anymore, but in typo3 I cannot add the oauth2 login method to the users.

**No OAuth2 configured**

Only the classes from typo3conf/ext/oauth2_client/Classes are added automatically.

The classes from /var/www/html/typo3/typo3conf/ext/oauth2_client/Resources/Private/PHP are missing.

Kind regards,
D

**Comment by dasoe** [comment]
Probably the same problem for me. 

`
Registered class League\OAuth2\Client\Provider\GenericProvider does not exist or is not an implementation of League\OAuth2\Client\Provider\AbstractProvider.
`

Docker Container typo3/10.4
oauth2-client installed via "get extension" in the extension manager

Thanks for any hint & have a good day

**Comment by maikschneider** [comment]
See my answer [here](https://github.com/waldhacker/ext-oauth2-client/issues/14#issuecomment-1366006145)

**Comment by waldhacker1** [comment]
The issue is fixed with version 2.0.2.
At the moment it is not possible to release into TER, but as soon as this is possible again, the extension can be used in non-composer TYPO3 installations.
