### ISSUE TITLE
Missing options param for getAuthorizationUrl

### ISSUE THREAD

**Issue by akiessling** [waldhacker/ext-oauth2-client#7]
When the authorization url is built up, the getAuthorizationUrl method expects the options to be passed on.
They are then passed on to getAuthorizationParameters to add the scope param to the url. 
see https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L386

https://github.com/waldhacker/ext-oauth2-client/blob/a68c8780e3dc4687bcf4f86a43bb53fb0a6ae293/Classes/Service/Oauth2Service.php#L50

I'm trying to integrate a 3rd party provider for Azure that does not set the defaultScope in the constructor and thus requires this to be passed on

**Comment by akiessling** [comment]
Guess i see why they were left out: simply passing on the whole option array adds all of them as params to the url. I'll patch the provider instead

**Comment by waldhacker1** [comment]
Thank you for your input. I am closing the ticket as I assume you were able to solve your problem yourself.
If not, please open a new ticket.

**Comment by akiessling** [comment]
Yes, you are right. I ended up not using your extension, but taking a lot of inspiration from it. My usecase and the "custom azure provider" just did not fit. Thanks a lot for publishing it!
