### ISSUE TITLE
QueryRestriction causes scheduler execution to fail

### ISSUE THREAD

**Issue by thopra** [waldhacker/ext-oauth2-client#8]
TYPO3 version 10.4
Extension version 2.0.0

When executing the scheduler, some tasks (not related to this extension) may fail while throwing the following exception:

`No valid attribute "applicationType" found in request object.`

This is caused by the enforced query restriction \Waldhacker\Oauth2Client\Database\Query\Restriction\Oauth2FeUserProviderConfigurationRestriction on line 51 because at that point in the scheduler, there is no valid TYPO3 request: 

```
if (
    ($GLOBALS['TYPO3_REQUEST'] ?? null) instanceof ServerRequestInterface
    && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend()
) {
    $this->isBackendUser = true;
}
```

Changing the condition to the following fixed the issue for me:

```
if (
    ($GLOBALS['TYPO3_REQUEST'] ?? null) instanceof ServerRequestInterface
    && $GLOBALS['TYPO3_REQUEST']->getAttribute('applicationType')
    && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isBackend()
) {
    $this->isBackendUser = true;
}
```

**Comment by waldhacker1** [comment]
Fixed in 2.0.1
